# Generated by Django 5.0.14 on 2026-09-07 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='floor',
            field=models.CharField(blank=True, max_length=20, verbose_name='Étage'),
        ),
    ]
