# Generated by Django 5.0.14 on 2026-09-11 11:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_user_floor_to_integer'),
    ]

    operations = [
    ]
