# Generated by Django 5.0.14 on 2026-09-07 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0001_initial'),
        ('rooms', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='attendees_count',
            field=models.PositiveIntegerField(default=1, help_text='Nombre de personnes attendues autour de la table', verbose_name='Nombre de personnes'),
        ),
        migrations.AddField(
            model_name='booking',
            name='requested_equipment',
            field=models.ManyToManyField(blank=True, help_text='Matériel supplémentaire nécessaire (webcam, écran, tablette...)', related_name='booking_requests', to='rooms.equipment', verbose_name='Matériel demandé'),
        ),
        migrations.AddField(
            model_name='booking',
            name='responsible_person',
            field=models.CharField(blank=True, help_text='Nom de la personne responsable / à contacter pour le matériel demandé', max_length=150, verbose_name='Personne en charge du matériel'),
        ),
    ]
