# Generated by Django 5.0.14 on 2026-09-07 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0002_booking_attendees_count_booking_requested_equipment_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='attendees_count',
            field=models.PositiveIntegerField(blank=True, default=1, help_text='Nombre de personnes attendues autour de la table', verbose_name='Nombre de personnes'),
        ),
    ]
