# Generated by Django 5.0.14 on 2026-09-08 04:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0003_alter_booking_attendees_count'),
        ('bookings', '0003_booking_floor'),
    ]

    operations = [
    ]
